import { PhoneNumber, Timestamp, Uuid, z } from './common.js';

/* ------------------------------------------------------------------ *
 * Device binding
 * ------------------------------------------------------------------ */

export const Platform = z.enum(['android', 'ios']);

/**
 * Everything we need to bind one courier account to exactly one handset.
 * `installationId` is generated by the app on first launch and persisted in
 * the Keychain / Keystore, so it survives app reinstall on iOS but not a
 * factory reset. It is the binding key, not the hardware id.
 */
export const DeviceInfo = z
  .object({
    installationId: Uuid,
    platform: Platform,
    osVersion: z.string().max(40),
    model: z.string().max(80).openapi({ example: 'SM-A546B' }),
    manufacturer: z.string().max(80).openapi({ example: 'samsung' }),
    appVersion: z.string().regex(/^\d+\.\d+\.\d+$/),
    appBuild: z.number().int().positive(),
    /**
     * OEM battery managers on these vendors kill background services. The app
     * reports it so the server can serve the right whitelist instructions.
     */
    batteryOptimizationExempt: z.boolean().nullish(),
  })
  .openapi('DeviceInfo');
export type DeviceInfo = z.infer<typeof DeviceInfo>;

/**
 * Play Integrity (Android) or App Attest (iOS) assertion. Verified server-side
 * and turned into a risk score. Deliberately never a hard block on its own:
 * a false positive would strand a courier mid-route.
 */
export const IntegrityAssertion = z
  .object({
    platform: Platform,
    token: z.string().min(1).max(8192),
    /** Client-generated nonce that the server issued in the previous call. */
    nonce: z.string().min(16).max(128),
  })
  .openapi('IntegrityAssertion');

export const IntegrityVerdict = z
  .object({
    score: z.number().min(0).max(100).describe('0 temiz, 100 kesin riskli'),
    signals: z.array(
      z.enum([
        'ROOTED_OR_JAILBROKEN',
        'EMULATOR',
        'UNRECOGNIZED_APP_SIGNATURE',
        'UNLICENSED_INSTALL',
        'MOCK_LOCATION_ENABLED',
        'HOOKING_FRAMEWORK',
        'ATTESTATION_UNAVAILABLE',
      ]),
    ),
    /** Server policy decision. `restrict` degrades features, never logs out. */
    action: z.enum(['allow', 'restrict', 'review']),
    evaluatedAt: Timestamp,
  })
  .openapi('IntegrityVerdict');

/* ------------------------------------------------------------------ *
 * Activation: phone -> OTP -> bound device
 * ------------------------------------------------------------------ */

export const ActivationStartRequest = z
  .object({
    phone: PhoneNumber,
    device: DeviceInfo,
  })
  .openapi('ActivationStartRequest');

export const ActivationStartResponse = z
  .object({
    challengeId: Uuid,
    /** Number of digits the UI should render. */
    codeLength: z.number().int().min(4).max(8).default(6),
    expiresAt: Timestamp,
    /** Client must disable the resend button until this instant. */
    resendAvailableAt: Timestamp,
    attemptsRemaining: z.number().int().nonnegative(),
    /**
     * Nonce to be embedded in the Play Integrity / App Attest assertion sent
     * with the verify call. Single use, bound to the challenge.
     */
    integrityNonce: z.string(),
  })
  .openapi('ActivationStartResponse');

export const ActivationVerifyRequest = z
  .object({
    challengeId: Uuid,
    code: z.string().regex(/^\d{4,8}$/),
    device: DeviceInfo,
    integrity: IntegrityAssertion.nullish(),
  })
  .openapi('ActivationVerifyRequest');

export const CourierProfile = z
  .object({
    id: Uuid,
    fullName: z.string(),
    phone: PhoneNumber,
    employeeCode: z.string().nullish(),
    branchId: Uuid.nullish(),
    branchName: z.string().nullish(),
    avatarUrl: z.string().url().nullish(),
    status: z.enum(['active', 'suspended', 'terminated']),
    /** Permissions the panel granted; drives feature visibility in the app. */
    capabilities: z.array(
      z.enum([
        'DELIVER',
        'PICKUP',
        'DOCUMENT_SCAN',
        'CASH_COLLECT',
        'CUSTODY_HANDOVER',
        'IDENTITY_CAPTURE',
      ]),
    ),
  })
  .openapi('CourierProfile');
export type CourierProfile = z.infer<typeof CourierProfile>;

export const TokenPair = z
  .object({
    accessToken: z.string(),
    /** Short lived on purpose: 15 minutes. Refresh rotates. */
    accessTokenExpiresAt: Timestamp,
    refreshToken: z.string(),
    refreshTokenExpiresAt: Timestamp,
  })
  .openapi('TokenPair');
export type TokenPair = z.infer<typeof TokenPair>;

export const ActivationVerifyResponse = z
  .object({
    tokens: TokenPair,
    courier: CourierProfile,
    integrity: IntegrityVerdict.nullish(),
    /** Permissions the app must request before the courier can open a shift. */
    requiredPermissions: z.array(
      z.enum([
        'LOCATION_ALWAYS',
        'LOCATION_WHEN_IN_USE',
        'CAMERA',
        'NOTIFICATIONS',
        'BATTERY_OPTIMIZATION_EXEMPTION',
      ]),
    ),
  })
  .openapi('ActivationVerifyResponse');

/* ------------------------------------------------------------------ *
 * Token rotation
 * ------------------------------------------------------------------ */

export const RefreshRequest = z
  .object({
    refreshToken: z.string(),
    installationId: Uuid,
  })
  .openapi('RefreshRequest');

/**
 * Refresh tokens are single use. Presenting a token that was already spent is
 * treated as theft: the whole family is revoked and the courier re-activates.
 * That is why the response can carry `familyRevoked`.
 */
export const RefreshResponse = z
  .object({
    tokens: TokenPair,
    familyRevoked: z.boolean().default(false),
  })
  .openapi('RefreshResponse');

export const LogoutRequest = z
  .object({
    installationId: Uuid,
    /** Revokes every session of this courier, not just this handset. */
    allDevices: z.boolean().default(false),
  })
  .openapi('LogoutRequest');

/* ------------------------------------------------------------------ *
 * Push registration
 * ------------------------------------------------------------------ */

export const PushTokenRequest = z
  .object({
    installationId: Uuid,
    provider: z.literal('fcm'),
    token: z.string().min(1),
  })
  .openapi('PushTokenRequest');
