import { sql } from 'drizzle-orm';
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  smallint,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

import { devicePlatform, integrityAction, otpChannel, otpPurpose } from './enums.js';
import { couriers } from './org.js';

export const devices = pgTable(
  'devices',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    courierId: uuid('courier_id')
      .notNull()
      .references(() => couriers.id, { onDelete: 'cascade' }),
    /** Generated by the app on first launch, stored in Keychain / Keystore. */
    installationId: uuid('installation_id').notNull(),
    platform: devicePlatform('platform').notNull(),
    osVersion: varchar('os_version', { length: 40 }).notNull(),
    model: varchar('model', { length: 80 }).notNull(),
    manufacturer: varchar('manufacturer', { length: 80 }).notNull(),
    appVersion: varchar('app_version', { length: 20 }).notNull(),
    appBuild: integer('app_build').notNull(),
    pushToken: varchar('push_token', { length: 512 }),
    batteryOptimizationExempt: boolean('battery_optimization_exempt'),
    /** Latest integrity verdict. Kept on the device, history goes to audit_log. */
    integrityScore: smallint('integrity_score'),
    integrityAction: integrityAction('integrity_action').default('allow'),
    integritySignals: jsonb('integrity_signals').$type<string[]>().notNull().default([]),
    integrityCheckedAt: timestamp('integrity_checked_at', { withTimezone: true }),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
    boundAt: timestamp('bound_at', { withTimezone: true }).notNull().defaultNow(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    revokedReason: varchar('revoked_reason', { length: 120 }),
  },
  (t) => ({
    installationUq: uniqueIndex('devices_installation_uq').on(t.installationId),
    /**
     * One live device per courier. Enforced as a partial unique index rather
     * than in application code, because a second bound handset would let the
     * same account report two locations at once.
     */
    activePerCourier: uniqueIndex('devices_active_courier_uq')
      .on(t.courierId)
      .where(sql`revoked_at is null`),
  }),
);

/**
 * Refresh token families. Rotation writes a new row and marks the parent used;
 * presenting an already-used token means the token leaked, so the whole family
 * (`familyId`) is revoked at once.
 */
export const sessions = pgTable(
  'sessions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    courierId: uuid('courier_id')
      .notNull()
      .references(() => couriers.id, { onDelete: 'cascade' }),
    deviceId: uuid('device_id')
      .notNull()
      .references(() => devices.id, { onDelete: 'cascade' }),
    familyId: uuid('family_id').notNull(),
    /** SHA-256 of the refresh token. The token itself is never stored. */
    refreshTokenHash: varchar('refresh_token_hash', { length: 64 }).notNull(),
    parentId: uuid('parent_id'),
    issuedAt: timestamp('issued_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    usedAt: timestamp('used_at', { withTimezone: true }),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    revokedReason: varchar('revoked_reason', { length: 120 }),
    ip: varchar('ip', { length: 45 }),
    userAgent: varchar('user_agent', { length: 255 }),
  },
  (t) => ({
    hashUq: uniqueIndex('sessions_refresh_hash_uq').on(t.refreshTokenHash),
    familyIdx: index('sessions_family_idx').on(t.familyId),
    liveIdx: index('sessions_live_idx')
      .on(t.courierId, t.expiresAt)
      .where(sql`revoked_at is null and used_at is null`),
  }),
);

/**
 * One row per OTP challenge, for both courier activation and recipient
 * verification at delivery. The code is hashed: a database dump must not let
 * anyone complete a delivery.
 */
export const otpChallenges = pgTable(
  'otp_challenges',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    purpose: otpPurpose('purpose').notNull(),
    channel: otpChannel('channel').notNull().default('sms'),
    /** E.164 target. For task OTP this is the recipient, not the courier. */
    phone: varchar('phone', { length: 20 }).notNull(),
    codeHash: varchar('code_hash', { length: 64 }).notNull(),
    /** Per-challenge salt so identical codes do not share a hash. */
    salt: varchar('salt', { length: 32 }).notNull(),
    courierId: uuid('courier_id').references(() => couriers.id, { onDelete: 'cascade' }),
    taskId: uuid('task_id'),
    stepKey: varchar('step_key', { length: 60 }),
    /** Nonce the client must embed in its Play Integrity / App Attest assertion. */
    integrityNonce: varchar('integrity_nonce', { length: 128 }),
    attempts: smallint('attempts').notNull().default(0),
    maxAttempts: smallint('max_attempts').notNull().default(5),
    sendCount: smallint('send_count').notNull().default(1),
    verifiedAt: timestamp('verified_at', { withTimezone: true }),
    consumedAt: timestamp('consumed_at', { withTimezone: true }),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    resendAvailableAt: timestamp('resend_available_at', { withTimezone: true }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    phonePurposeIdx: index('otp_phone_purpose_idx').on(t.phone, t.purpose, t.createdAt),
    taskIdx: index('otp_task_idx').on(t.taskId),
    liveIdx: index('otp_live_idx')
      .on(t.expiresAt)
      .where(sql`consumed_at is null`),
  }),
);
